django_movies/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from accounts.views import (SubmittableLoginView, 
SuccessMessagedLogoutView, SubmittablePasswordChangeView, SignUpView)

app_name='accounts'

urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name="login"),
    path('logout/', SuccessMessagedLogoutView.as_view(), name="logout"),
    path('password_change/', SubmittablePasswordChangeView.as_view(), name="password_change"),
    path('signup/', SignUpView.as_view(), name="signup")
]

django_movies/core/urls.py
from django.urls import path
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView, MovieListView, MovieDetailView

app_name = 'core'
urlpatterns = [
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView
from .views import IndexView

app_name='app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('core/', include('core.urls', namespace="core")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

django_movies/django_movies/views.py
from core.views import MovieListView

class IndexView(MovieListView):
    template_name='index.html'

django_movies/django_movies/templates/base.html
{% comment %}
{% load bootstrap4 %}
​
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>
​
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
  <body style="min-height: 150vh;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-success sticky-top">
      <div class="container fixed">
      <a class="navbar-brand" href="/">Django Movies</a>
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="display:flex; justify-content: space-around;">
          <div class="navbar-nav" style="display:flex; justify-content: space-around; width: 100%;">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
            <a class="nav-item nav-link active" href="{% url 'core:movie_list' %}">
              List
            </a>
            <a class="nav-item nav-link active" href="{% url 'core:movie_create' %}">
              Add Movie
            </a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
  {% endcomment %}

{% load bootstrap4 %}
{% load static %}
​
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>
​
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
  ​<style>
    .xd:hover {
      color: white;
      background-color: #343a40;
    }
  </style>

  <body id="layout">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
            <div class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                Movies
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item xd" href="{% url 'core:movie_list' %}">List</a>
                <a class="dropdown-item xd" href="{% url 'core:movie_create' %}">Create</a>
              </div>
            </div>
          </div>
          <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  {% if user.first_name %}Hello, {{ user.first_name }}!
                  {% else %}Hello, {{ user.username }}!{% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'accounts:logout' %}" class="dropdown-item text-right logged-out xd">Logout</a>
                  <a href="{% url 'accounts:password_change' %}" class="dropdown-item text-right xd">Change Password</a>
                </div>
              {% else %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  You are not logged in.
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right xd" href="{% url 'accounts:login' %}">Login</a>
                  <a class="dropdown-item text-right xd" href="{% url 'accounts:signup' %}">Sign Up</a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>


  <script>
    const message = () => {
      // const alert = document.createElement('div');
      // alert.textContent = 'Logged Out';
      // alert.style.fontSize = '50px';
      // alert.style.color = 'green';
      // document.querySelector('#layout').appendChild(alert);
      alert('Logged out');
    }
    const logoutBtn = document.querySelector('.logged-out');

    if (logoutBtn) {
      logoutBtn.addEventListener('click', message);
    }
  </script>
​
</html>

django_movies/django_movies/templates/form.html
{% extends "base.html" %}
​
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}

django_movies/django_movies/templates/index.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}

  <ul class="list-group">
    {% for movie in object_list %}
      <li class="list-group-item" style="display:flex; justify-content: space-between;">
        {% movie_format movie %}
      </li>
    {% endfor %}
  </ul>

  {% comment %} <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav> {% endcomment %}

{% endblock %}