django_movies/core/urls.py
from django.urls import path
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView, MovieListView, MovieDetailView

app_name = 'core'
urlpatterns = [
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView
from .views import IndexView

app_name='app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('core/', include('core.urls', namespace="core")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

django_movies/core/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from model_utils import Choices

AGE_LIMITS = Choices(
    (0, 'kids', 'kids'),
    (1, 'teens', 'teens'),
    (2, 'adults', 'adults'),
)

class Country(models.Model):
    name = models.CharField(max_length=20, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    

class Genre(models.Model):
    name = models.CharField(max_length=20, unique=True)
    age_limit = models.IntegerField(null=True, blank=True, choices=AGE_LIMITS)

    def __str__(self):
        return self.name

class Director(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)

    class Meta:
        unique_together = ('name', 'surname')

    def __str__(self):
        return f"{self.name} {self.surname}"
    

class Movie(models.Model):
    title = models.CharField(max_length=100)
    rating = models.IntegerField(
        null=True, validators=[MaxValueValidator(15), MinValueValidator(1)]
    )
    released = models.DateField()
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL)
    director = models.ForeignKey(Director, null=True, on_delete=models.SET_NULL)
    countries = models.ManyToManyField(Country, related_name='movies')

    class Meta:
        unique_together = ('title', 'released')

    def __str__(self):
        return f"{self.title} from {self.released}"
    

django_movies/core/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from datetime import date
from core.models import Genre, Movie
from django.core.exceptions import ValidationError
import re

def capitalized_validator(value: str):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


class PastMonthField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=result.day)

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

    title = forms.CharField(validators=[capitalized_validator])
    rating = forms.IntegerField(min_value=1, max_value=10)
    released = PastMonthField()
    # genre = forms.ModelChoiceField(queryset=Genre.objects.all())
    # description = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('genre'), Column('rating'), Column('released')),
            'director',
            'description',
            'countries',
            Submit('submit', 'Submit'),
        )

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '. '.join(sentence.capitalize() for sentence in sentences)
        return cleaned

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'comedy' and result['rating'] > 5:
            raise ValidationError('The best comedy is worth a 4.')
        return result

django_movies/core/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django.http import HttpResponse
from core.models import Movie, AGE_LIMITS
from core.forms import MovieForm
from django.urls import reverse_lazy
import logging
from django import views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin


logging.basicConfig(
    filename='log.txt', 
    filemode='w',
    level=logging.INFO,
    )

LOGGER = logging.getLogger(__name__)

class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

class MovieCreateView(StaffRequiredMixin, LoginRequiredMixin, CreateView):
    template_name='form.html'
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        result = super().post(request, *args, **kwargs)
        LOGGER.info(f"Succesfully added {request.__dict__['_post']['title']}")
        return result

class MovieUpdateView(StaffRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name='form.html'
    form_class = MovieForm
    model = Movie
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)

    def test_func(self):
        super().test_func()
        return self.request.user.is_superuser

class MovieDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name='delete.html'
    model = Movie
    success_url = reverse_lazy('core:movie_list')

    def test_func(self):
        super().test_func()
        return self.request.user.is_superuser

class MovieListView(ListView):
    template_name='movie_list.html'
    model = Movie

class MovieDetailView(DetailView):
    template_name='movie_detail.html'
    model = Movie

# class IndexView(MovieListView):
#     template_name='index.html'

django_movies/core/templates/base.html
{% load bootstrap4 %}
{% load static %}
​
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>
​
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
​
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
      {% comment %} <a class="navbar-brand" href="/">Django Movies</a> {% endcomment %}
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

django_movies/core/templates/delete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
  <form method="post">
      {% csrf_token %}
        <p><center>
            Are you sure you want to delete movie "{{ object.title }}" from the database?
        </center></p>
        <div class="btn-group btn-block" role="group" aria-label="Delete decision">
            <button type="submit" class="btn btn-success">Yes</button>
            <button type="button" onclick="history.go(-1);" class="btn btn-danger">No</button>
        </div>
  </form>
{% endblock %}

django_movies/core/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Hello, world</title>
</head>
    <body>
        <h1>Hello, my friend...</h1>
        {% for adjective in adjectives %}
            {% if adjective != 'cruel' %}
                <p>This is a {{ adjective }} world...</p>
            {% endif %}
        {% endfor %}
    </body>
</html>

django_movies/core/templates/movie_detail.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  {{ movie|attr_as_p:'title' }}
  {{ movie|attr_as_p:'released' }}
  {{ movie|attr_as_p:'genre' }}
  {{ movie|attr_as_p:'rating' }}
  {{ movie|attr_as_p:'description' }}
{% endblock %}

django_movies/core/templates/movie_list.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  <ul ul class="list-group">
    {% for movie in object_list %}
      <li class="list-group-item" style="display:flex; justify-content: space-between;">
        {% movie_format movie short=True %}
        <div>
          <button class="btn" style="padding:0; margin: 0;">
            <a class="update" href="{% url 'core:movie_detail' movie.pk %}" style="padding:0; margin: 0; width: 100%">
              🔎
            </a>
          </button>
          <button class="btn" style="padding:0; margin: 0;">
            <a class="update" href="{% url 'core:movie_update' movie.pk %}" style="padding:0; margin: 0; width: 100%">
              🖊️
            </a>
          </button>
          <button class="btn" style="padding:0; margin: 0;">
            <a class="remove" href="{% url 'core:movie_delete' movie.pk %}" style="padding:0; margin: 0; width: 100%">
              ❌
            </a>
          </button>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

django_movies/core/templates/movies.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-5">Welcome to Django Movies!</h1>
    <ul class="list-group">
        {% for movie in object_list %}
            {% if movie.genre.age_limit != limits.adults %}
                <li class="list-group-item" style="display:flex; justify-content: space-between;">
                    {{ movie.title }} ({{ movie.released.year }}) - director: {{movie.director}}, genre: {{ movie.genre.name }}, age category: {{ movie.genre.get_age_limit_display }}
                    <div>
                        <button class="btn" style="padding:0; margin: 0;">
                            <a class="update" href="/movie/update/{{movie.id}}" style="padding:0; margin: 0; width: 100%">
                                🖊️
                            </a>
                        </button>
                        <button class="btn" style="padding:0; margin: 0;">
                            <a class="remove" href="/movie/update/{{movie.id}}" style="padding:0; margin: 0; width: 100%">
                                ❌
                            </a>
                        </button>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}